### ISSUE TITLE
Tell me why `.js` file works like` .tsx` file.

### ISSUE THREAD

**Issue by 1amageek** [stripe/react-stripe#1]
Thank you for a great project.

I have a question. I cloned and tried this project.
Tell me why `.js` file works like` .tsx` file.

I'm not developing well in my development environment.😭

<img width="655" alt="スクリーンショット 2019-12-05 18 07 15" src="https://user-images.githubusercontent.com/11146538/70220540-18f73000-178a-11ea-94b5-b8eee4995964.png">

**Comment by 1amageek** [comment]
I learned about Flow. But I don't know why this project uses Flow instead of TypeScript.
I am interested in the reason.

**Comment by dweedon-stripe** [comment]
Hi @1amageek!

Thanks for your interest. We use Flow because Stripe uses a lot of Flow internally.

Keep in mind that if you are building anything with this library right now that it is in an alpha state and there might be a bit of churn until we are ready to release more broadly.
